export const FETCH_SUMMARY_PENDING = "FETCH_SUMMARY_PENDING";
export const FETCH_SUMMARY_SUCCESS = "FETCH_SUMMARY_SUCCESS";
export const FETCH_SUMMARY_ERROR = "FETCH_SUMMARY_ERROR";
export const CLEAR_SUMMARY = "CLEAR_SUMMARY";