// src/store/courseSummary/courseSummaryActionTypes.js

export const FETCH_COURSE_SUMMARY_PENDING = "FETCH_COURSE_SUMMARY_PENDING";
export const FETCH_COURSE_SUMMARY_SUCCESS = "FETCH_COURSE_SUMMARY_SUCCESS";
export const FETCH_COURSE_SUMMARY_ERROR = "FETCH_COURSE_SUMMARY_ERROR";

export const RESET_COURSE_SUMMARY = "RESET_COURSE_SUMMARY";