// src/store/physicalProficiency/PhysicalProficiencyActionTypes.js

export const SUBMIT_PHYSICAL_PROFICIENCY_PENDING = "SUBMIT_PHYSICAL_PROFICIENCY_PENDING";
export const SUBMIT_PHYSICAL_PROFICIENCY_SUCCESS = "SUBMIT_PHYSICAL_PROFICIENCY_SUCCESS";
export const SUBMIT_PHYSICAL_PROFICIENCY_ERROR = "SUBMIT_PHYSICAL_PROFICIENCY_ERROR";

export const FETCH_PHYSICAL_PROFICIENCY_PENDING = "FETCH_PHYSICAL_PROFICIENCY_PENDING";
export const FETCH_PHYSICAL_PROFICIENCY_SUCCESS = "FETCH_PHYSICAL_PROFICIENCY_SUCCESS";
export const FETCH_PHYSICAL_PROFICIENCY_ERROR = "FETCH_PHYSICAL_PROFICIENCY_ERROR";

export const UPDATE_PHYSICAL_PROFICIENCY_PENDING = "UPDATE_PHYSICAL_PROFICIENCY_PENDING";
export const UPDATE_PHYSICAL_PROFICIENCY_SUCCESS = "UPDATE_PHYSICAL_PROFICIENCY_SUCCESS";
export const UPDATE_PHYSICAL_PROFICIENCY_ERROR = "UPDATE_PHYSICAL_PROFICIENCY_ERROR";

export const CLEAR_PHYSICAL_PROFICIENCY = "CLEAR_PHYSICAL_PROFICIENCY";