export const masterActionTypes = {
  FETCH_ROLES_PENDING: "FETCH_ROLES_PENDING",
  FETCH_ROLES_SUCCESS: "FETCH_ROLES_SUCCESS",
  FETCH_ROLES_ERROR: "FETCH_ROLES_ERROR",

  FETCH_TRADES_PENDING: "FETCH_TRADES_PENDING",
  FETCH_TRADES_SUCCESS: "FETCH_TRADES_SUCCESS",
  FETCH_TRADES_ERROR: "FETCH_TRADES_ERROR",

  FETCH_COURSES_PENDING: "FETCH_COURSES_PENDING",
  FETCH_COURSES_SUCCESS: "FETCH_COURSES_SUCCESS",
  FETCH_COURSES_ERROR: "FETCH_COURSES_ERROR",
};
