export const FETCH_OFC_TECH_PHASE_PENDING = "FETCH_OFC_TECH_PHASE_PENDING";
export const FETCH_OFC_TECH_PHASE_SUCCESS = "FETCH_OFC_TECH_PHASE_SUCCESS";
export const FETCH_OFC_TECH_PHASE_ERROR = "FETCH_OFC_TECH_PHASE_ERROR";

export const SAVE_OFC_TECH_PHASE_PENDING = "SAVE_OFC_TECH_PHASE_PENDING";
export const SAVE_OFC_TECH_PHASE_SUCCESS = "SAVE_OFC_TECH_PHASE_SUCCESS";
export const SAVE_OFC_TECH_PHASE_ERROR = "SAVE_OFC_TECH_PHASE_ERROR";

export const CLEAR_OFC_TECH_PHASE = "CLEAR_OFC_TECH_PHASE";