
export const FETCH_GUNNER_TECH_PHASE_PENDING = "FETCH_GUNNER_TECH_PHASE_PENDING";
export const FETCH_GUNNER_TECH_PHASE_SUCCESS = "FETCH_GUNNER_TECH_PHASE_SUCCESS";
export const FETCH_GUNNER_TECH_PHASE_ERROR = "FETCH_GUNNER_TECH_PHASE_ERROR";

export const SAVE_GUNNER_TECH_PHASE_PENDING = "SAVE_GUNNER_TECH_PHASE_PENDING";
export const SAVE_GUNNER_TECH_PHASE_SUCCESS = "SAVE_GUNNER_TECH_PHASE_SUCCESS";
export const SAVE_GUNNER_TECH_PHASE_ERROR = "SAVE_GUNNER_TECH_PHASE_ERROR";

export const CLEAR_GUNNER_TECH_PHASE = "CLEAR_GUNNER_TECH_PHASE";