export const FETCH_OPERATOR_TECH_PHASE_PENDING = "FETCH_OPERATOR_TECH_PHASE_PENDING";
export const FETCH_OPERATOR_TECH_PHASE_SUCCESS = "FETCH_OPERATOR_TECH_PHASE_SUCCESS";
export const FETCH_OPERATOR_TECH_PHASE_ERROR = "FETCH_OPERATOR_TECH_PHASE_ERROR";

export const SAVE_OPERATOR_TECH_PHASE_PENDING = "SAVE_OPERATOR_TECH_PHASE_PENDING";
export const SAVE_OPERATOR_TECH_PHASE_SUCCESS = "SAVE_OPERATOR_TECH_PHASE_SUCCESS";
export const SAVE_OPERATOR_TECH_PHASE_ERROR = "SAVE_OPERATOR_TECH_PHASE_ERROR";

export const CLEAR_OPERATOR_TECH_PHASE = "CLEAR_OPERATOR_TECH_PHASE";