export const LOAD_COURSES = "LOAD_COURSES";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_COURSES_FAILURE = "LOAD_COURSES_FAILURE";

export const GET_COURSE_BY_ID_PENDING = "GET_COURSE_BY_ID_PENDING";
export const GET_COURSE_BY_ID_SUCCESS = "GET_COURSE_BY_ID_SUCCESS";
export const GET_COURSE_BY_ID_ERROR = "GET_COURSE_BY_ID_ERROR";

export const ADD_COURSE_PENDING = "ADD_COURSE_PENDING";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_ERROR = "ADD_COURSE_ERROR";

export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const RESET_COURSES_PAGINATION="RESET_COURSES_PAGINATION";