export const FETCH_DRIVER_TECH_PHASE_PENDING = "FETCH_DRIVER_TECH_PHASE_PENDING";
export const FETCH_DRIVER_TECH_PHASE_SUCCESS = "FETCH_DRIVER_TECH_PHASE_SUCCESS";
export const FETCH_DRIVER_TECH_PHASE_ERROR = "FETCH_DRIVER_TECH_PHASE_ERROR";

export const SAVE_DRIVER_TECH_PHASE_PENDING = "SAVE_DRIVER_TECH_PHASE_PENDING";
export const SAVE_DRIVER_TECH_PHASE_SUCCESS = "SAVE_DRIVER_TECH_PHASE_SUCCESS";
export const SAVE_DRIVER_TECH_PHASE_ERROR = "SAVE_DRIVER_TECH_PHASE_ERROR";

export const CLEAR_DRIVER_TECH_PHASE = "CLEAR_DRIVER_TECH_PHASE";