// SYSTEM USER ACTION TYPES

export const LOAD_SYSTEM_USERS = "LOAD_SYSTEM_USERS";

export const GET_SYSTEM_USER_BY_ID_PENDING = "GET_SYSTEM_USER_BY_ID_PENDING";
export const GET_SYSTEM_USER_BY_ID_SUCCESS = "GET_SYSTEM_USER_BY_ID_SUCCESS";
export const GET_SYSTEM_USER_BY_ID_ERROR = "GET_SYSTEM_USER_BY_ID_ERROR";

export const ADD_SYSTEM_USER_PENDING = "ADD_SYSTEM_USER_PENDING";
export const ADD_SYSTEM_USER_SUCCESS = "ADD_SYSTEM_USER_SUCCESS";
export const ADD_SYSTEM_USER_ERROR = "ADD_SYSTEM_USER_ERROR";

export const UPDATE_SYSTEM_USER = "UPDATE_SYSTEM_USER";
export const DELETE_SYSTEM_USER = "DELETE_SYSTEM_USER";
export const RESET_SYSTEM_USERS_PAGINATION = "RESET_SYSTEM_USERS_PAGINATION";

