// TRADE USER ACTION TYPES

export const CREATE_AGNIVEER_PENDING = "CREATE_AGNIVEER_PENDING";
export const CREATE_AGNIVEER_SUCCESS = "CREATE_AGNIVEER_SUCCESS";
export const CREATE_AGNIVEER_ERROR = "CREATE_AGNIVEER_ERROR";

export const LOAD_AGNIVEERS = "LOAD_AGNIVEERS";

export const GET_AGNIVEERS_PENDING = "GET_AGNIVEERS_PENDING";
export const GET_AGNIVEERS_SUCCESS = "GET_AGNIVEERS_SUCCESS";
export const GET_AGNIVEERS_ERROR = "GET_AGNIVEERS_ERROR";



export const GET_SINGLE_AGNIVEER_PENDING = "GET_SINGLE_AGNIVEER_PENDING";
export const GET_SINGLE_AGNIVEER_SUCCESS = "GET_SINGLE_AGNIVEER_SUCCESS";
export const GET_SINGLE_AGNIVEER_ERROR = "GET_SINGLE_AGNIVEER_ERROR";

export const EXPORT_AGNIVEERS_PENDING = "EXPORT_AGNIVEERS_PENDING";
export const EXPORT_AGNIVEERS_SUCCESS = "EXPORT_AGNIVEERS_SUCCESS";
export const EXPORT_AGNIVEERS_ERROR = "EXPORT_AGNIVEERS_ERROR";

export const IMPORT_AGNIVEERS_PENDING = "IMPORT_AGNIVEERS_PENDING";
export const IMPORT_AGNIVEERS_SUCCESS = "IMPORT_AGNIVEERS_SUCCESS";
export const IMPORT_AGNIVEERS_ERROR = "IMPORT_AGNIVEERS_ERROR";