export const actionTypes = {
  AUTH_PENDING: "AUTH_PENDING",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_ERROR:"AUTH_ERROR",

  CHANGE_PASSWORD_PENDING: "CHANGE_PASSWORD_PENDING",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_ERROR: "CHANGE_PASSWORD_ERROR",

  RESET_PASSWORD: "RESET_PASSWORD",

  FORGOT_PASSWORD: "FORGOT_PASSWORD",

  UPDATE_TOKEN_SUCCESS: "UPDATE_TOKEN_SUCCESS",

  LOGOUT_PENDING: "LOGOUT_PENDING",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_ERROR: "LOGOUT_ERROR",
};