export const FETCH_DASHBOARD_PENDING = "FETCH_DASHBOARD_PENDING";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_ERROR = "FETCH_DASHBOARD_ERROR";
export const CLEAR_DASHBOARD = "CLEAR_DASHBOARD";


export const FETCH_TRADE_DASHBOARD_PENDING = "FETCH_TRADE_DASHBOARD_PENDING";
export const FETCH_TRADE_DASHBOARD_SUCCESS = "FETCH_TRADE_DASHBOARD_SUCCESS";
export const FETCH_TRADE_DASHBOARD_ERROR = "FETCH_TRADE_DASHBOARD_ERROR";
export const CLEAR_TRADE_DASHBOARD = "CLEAR_TRADE_DASHBOARD";
